### ISSUE TITLE
The list of elements does not appear in React 

### ISSUE THREAD

**Issue by DiegoGrandeAlagon** [vaadin/vaadin-select#202]
### Description
The list of elements is not loaded in the  React application. If I remove  the tag \<template\> the list is loaded but the  selected item does not appear.

#### Steps to Reproduce
1. Create `vaadin-select`
2. Create\<template\> and append to 'vaadin-select'
3. Append `vaadin-list-box`  with `vaadin-item` to \<template\>

Example:
\<vaadin-select value="Henry"\>
&nbsp;&nbsp;\<template\>
&nbsp;&nbsp;&nbsp;&nbsp;\<vaadin-list-box\>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<vaadin-item\>Jose\</vaadin-item\>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<vaadin-item\>Henry\</vaadin-item\>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<vaadin-item\>Pedro\</vaadin-item\>
&nbsp;&nbsp;&nbsp;&nbsp;\</vaadin-list-box\>
&nbsp;&nbsp; \</template\>
\</vaadin-select\>

#### Expected Results

![image](https://user-images.githubusercontent.com/18046046/60517421-f4c98b80-9cdf-11e9-985c-31e52d796bda.png)

#### Actual Results
![image](https://user-images.githubusercontent.com/18046046/60516927-0a8a8100-9cdf-11e9-856e-9afcc73d5adc.png)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge

**Comment by tomivirkki** [comment]
The Polymer-heavy `<template>` APIs should generally be avoided in React applications (due to the problems you encountered). The preferred framework-agnostic [`renderer` API](https://cdn.vaadin.com/vaadin-select/2.1.5/demo/#select-basic-demos) is more verbose but works better in non-Polymer apps.

See [this tutorial](https://vaadin.com/tutorials/using-web-components-in-react) for more information on using Vaadin components with React. Note that Custom Elements in React [has compatibility issues in general](https://custom-elements-everywhere.com#react).

I'm also working on trying to solve these issues [in this (still at 0.X) project](https://github.com/tomivirkki/react-vaadin-components)
