### ISSUE TITLE
Represent selected value as components

### ISSUE THREAD

**Issue by tanbt** [vaadin/vaadin-select#208]
### Description
[Value attribute](https://vaadin.com/components/vaadin-select/html-examples/select-basic-demos#customize-the-label-of-selected-value) allows replacing visual representation of selected value by another text.
But I want to represent the selected value beautifully as well. 

#### Live Demo
In the menu, I have beautiful items (with icon, text, span), when an item is selected, I only want to show its icon and text in vaadin-select input field.

![image](https://user-images.githubusercontent.com/4935326/64604981-da8ce780-d3cb-11e9-8327-b0f16df770ef.png)

#### Expected Results
Icon is displayed.

#### Actual Results
HTML inserted into `label` will be rendered as-is.
A workaround is to use `suffix`.
Slack: https://vaadin.slack.com/archives/C3TGRP4HY/p1568102084174300

### Browsers Affected
- [ ] Chrome

### Versions
- vaadin-select: v2.0.4

**Comment by web-padawan** [comment]
This is what the [demo](https://vaadin.com/components/vaadin-select/html-examples/select-presentation-demos) says now:

> By setting label properties for the vaadin-item elements you can override the default visual representation of the selected item and make the vaadin-select show the item's label instead.

And here is how it actually works:

> https://github.com/vaadin/vaadin-select/blob/81e0c22fe858d702b790e67cd08eb3a5b31f73d1/src/vaadin-select.html#L560-L565

If you set `label` it will be used. Otherwise the selected `vaadin-item` is cloned and inserted.
The latter (cloning the item) is how views selector now works at https://start.vaadin.com

So, the requested feature is doable. Therefore I'm closing this issue as won't fix.
But please feel free to comment if something is unclear or has to be improved.
