### ISSUE TITLE
Use with vaadin-button

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-select#92]
I need a button with a dropdown (e.g. [Bootstrap Dropdowns](https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns)).

Can I use this element with `vaadin-button` to achieve this, or there will be (or not) another element for such use cases?

**Comment by jouni** [comment]
As a workaround for now, I would suggest you wrap a `<vaadin-button>` with `<vaadin-context-menu>`. Should get you quite far.

**Comment by heruan** [comment]
@jouni I'm facing many scenarios where I need a dropdown for different components, not only text fields and buttons, but also e.g. your `j-avatar` element. How about rename this issue to a more generic "Use with other components"?

Than, do you feel it would be doable to slot the text-field and provide a "light" dropdown menu?

I think this is really needed (the context menu workaround is good but not always consistent with the expected behavior, e.g. positioning).

**Comment by jouni** [comment]
Yeah, that’s a good observation.

My leaning is more towards adding more capability to context menu so that the positioning could be controlled more precisely. Then, perhaps, we could use that inside dropdown-menu instead of duplicating the overlay implementation.

I’d have to spend a bit more time playing around with different use cases and pseudo-code to form a better opinion about this.

**Comment by heruan** [comment]
I'm closing this since it's not really related to selection, which is what this component is all about.
